from pathlib import Path
from html import escape
import re
import calendar
from datetime import date, datetime, timedelta
from collections import defaultdict

import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

ROOT = Path(__file__).resolve().parent
INSTRUCTOR_INPUTS = ROOT / "instructor_inputs"
GENERATED_OUTPUTS = ROOT / "generated_outputs"
LECTURE_FILE = INSTRUCTOR_INPUTS / "lecture_summary.md"
LAB_FILE = INSTRUCTOR_INPUTS / "lab_summary.md"
QUIZ_SCHEDULE_FILE = INSTRUCTOR_INPUTS / "quiz_schedule.md"
IMPORTANT_DATES_FILE = INSTRUCTOR_INPUTS / "important_dates.md"
XLSX_FILE = GENERATED_OUTPUTS / "Weekly Schedules.xlsx"
OUTPUT_SHEET = "AutoGenerated Schedule"
OUTPUT_MD = GENERATED_OUTPUTS / "weekly_schedule.md"
OUTPUT_CALENDAR_MD = GENERATED_OUTPUTS / "calendar_schedule.md"
OUTPUT_ICS = GENERATED_OUTPUTS / "course_calendar.ics"

TERM_YEAR = 2026
CALENDAR_WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
DEFAULT_LECTURE_WEEKDAYS = [0, 2, 4]
DEFAULT_LAB_WEEKDAYS = [1]
DEFAULT_LAB_DELIVERABLE_WEEKDAYS = [1]
DEFAULT_DISCUSSION_WEEKDAYS = [3]
DEFAULT_OFFICE_HOURS_WEEKDAYS = [4]
DEFAULT_HOMEWORK_WEEKDAYS = [6]
DEFAULT_EVENT_TIMES = {
    "lecture": ("11:15 AM", "12:05 PM"),
    "lab": ("", ""),
    "lab_deliverable": ("9:55 PM", "10:00 PM"),
    "discussion": ("12:20 PM", "1:10 PM"),
    "office_hours": ("3:00 PM", "5:00 PM"),
    "homework": ("2:55 PM", "3:00 PM"),
}
LOCAL_TIMEZONE = "America/New_York"
FLAGGABLE_IMPORTANT_DATE = re.compile(
    r"holiday|classes suspended|recess|substitute|classes resume|study period|last day of classes",
    re.IGNORECASE,
)
WEEKDAY_NUMBERS = {
    "monday": 0,
    "mon": 0,
    "tuesday": 1,
    "tue": 1,
    "tues": 1,
    "wednesday": 2,
    "wed": 2,
    "thursday": 3,
    "thu": 3,
    "thurs": 3,
    "friday": 4,
    "fri": 4,
    "saturday": 5,
    "sat": 5,
    "sunday": 6,
    "sun": 6,
}


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def normalize_dash(text: str) -> str:
    return text.replace("–", "-").replace("—", "-")


def parse_month_day(month_day: str, default_year: int) -> date:
    m = re.match(r"^([A-Za-z]+)\s+(\d{1,2})$", month_day.strip())
    if not m:
        raise ValueError(f"Could not parse date: {month_day}")

    month_name, day = m.groups()
    month = list(calendar.month_name).index(month_name)
    year = default_year if month >= 8 else default_year + 1
    return date(year, month, int(day))


def split_markdown_table_row(line: str):
    if not line.startswith("|") or not line.endswith("|"):
        return None
    return [cell.strip() for cell in line.strip("|").split("|")]


def is_markdown_separator(cells):
    return all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells)


def extract_table_after_heading(lines, heading: str):
    in_section = False
    table = []
    heading_pattern = re.compile(rf"^##\s+{re.escape(heading)}\s*$", re.IGNORECASE)

    for raw in lines:
        line = raw.rstrip()
        if heading_pattern.match(line):
            in_section = True
            continue
        if not in_section:
            continue
        if line.startswith("## ") and table:
            break

        cells = split_markdown_table_row(clean_text(line))
        if cells:
            table.append(cells)
        elif table:
            break

    if not table:
        return []

    headers = None
    rows = []
    for cells in table:
        if is_markdown_separator(cells):
            continue
        if headers is None:
            headers = [cell.lower() for cell in cells]
            continue
        rows.append(dict(zip(headers, cells)))
    return rows


def parse_weekday_list(text: str):
    weekdays = []
    parts = re.split(r",|/|;|\band\b", text, flags=re.IGNORECASE)
    for part in parts:
        key = clean_text(part).lower()
        if key in WEEKDAY_NUMBERS:
            weekdays.append(WEEKDAY_NUMBERS[key])
    return weekdays


def normalize_event_time(text: str):
    text = clean_text(text)
    if not text:
        return ""
    for fmt in ("%I:%M %p", "%I %p", "%H:%M"):
        try:
            return datetime.strptime(text.upper(), fmt).strftime("%I:%M %p").lstrip("0")
        except ValueError:
            continue
    return text


def read_row_time(row, fallback):
    start = normalize_event_time(row.get("start time", ""))
    end = normalize_event_time(row.get("end time", ""))
    if not start and not end:
        start, end = fallback
    return start, end


def event_time_range(meeting_patterns, event_key: str):
    return meeting_patterns.get("times", {}).get(event_key, DEFAULT_EVENT_TIMES[event_key])


def format_time_range(start: str, end: str):
    if start and end:
        return f"{start}-{end}"
    if end:
        return f"Due {end}"
    if start:
        return f"Starts {start}"
    return ""


def time_for_ics(event_date: date, time_text: str):
    parsed = datetime.strptime(normalize_event_time(time_text), "%I:%M %p")
    return datetime.combine(event_date, parsed.time())


def parse_meeting_patterns(lecture_path: Path, lab_path: Path):
    patterns = {
        "lecture": DEFAULT_LECTURE_WEEKDAYS,
        "lab": DEFAULT_LAB_WEEKDAYS,
        "lab_deliverable": DEFAULT_LAB_DELIVERABLE_WEEKDAYS,
        "discussion": DEFAULT_DISCUSSION_WEEKDAYS,
        "office_hours": DEFAULT_OFFICE_HOURS_WEEKDAYS,
        "homework": DEFAULT_HOMEWORK_WEEKDAYS,
        "times": DEFAULT_EVENT_TIMES.copy(),
        "office_hour_patterns": [],
    }

    lecture_rows = extract_table_after_heading(
        lecture_path.read_text(encoding="utf-8").splitlines(),
        "Course Meeting Pattern",
    )
    for row in lecture_rows:
        event_type = row.get("event type", "").lower()
        weekdays = parse_weekday_list(row.get("weekdays", ""))
        if not weekdays:
            continue
        if event_type == "lecture":
            patterns["lecture"] = weekdays
            patterns["times"]["lecture"] = read_row_time(row, DEFAULT_EVENT_TIMES["lecture"])
        elif event_type == "discussion":
            patterns["discussion"] = weekdays
            patterns["times"]["discussion"] = read_row_time(row, DEFAULT_EVENT_TIMES["discussion"])
        elif re.fullmatch(r"office hours?", event_type) or event_type.startswith("office hour "):
            patterns["office_hours"] = weekdays
            patterns["times"]["office_hours"] = read_row_time(row, DEFAULT_EVENT_TIMES["office_hours"])
            patterns["office_hour_patterns"].append(
                {
                    "title": row.get("event type", "Office Hours"),
                    "weekdays": weekdays,
                    "start_time": patterns["times"]["office_hours"][0],
                    "end_time": patterns["times"]["office_hours"][1],
                }
            )
        elif event_type == "homework":
            patterns["homework"] = weekdays
            patterns["times"]["homework"] = read_row_time(row, DEFAULT_EVENT_TIMES["homework"])

    lab_rows = extract_table_after_heading(
        lab_path.read_text(encoding="utf-8").splitlines(),
        "Lab Meeting Pattern",
    )
    for row in lab_rows:
        event_type = row.get("event type", "").lower()
        weekdays = parse_weekday_list(row.get("weekday", "") or row.get("weekdays", ""))
        if weekdays and event_type in {"lab", "lab / project", "lab/project", "project"}:
            patterns["lab"] = weekdays
            patterns["times"]["lab"] = read_row_time(row, DEFAULT_EVENT_TIMES["lab"])
        elif weekdays and event_type in {"lab deliverable", "lab deliverables", "deliverable", "deliverables"}:
            patterns["lab_deliverable"] = weekdays
            patterns["times"]["lab_deliverable"] = read_row_time(row, DEFAULT_EVENT_TIMES["lab_deliverable"])

    if not patterns["office_hour_patterns"]:
        start_time, end_time = event_time_range(patterns, "office_hours")
        patterns["office_hour_patterns"].append(
            {
                "title": "Office Hours",
                "weekdays": patterns["office_hours"],
                "start_time": start_time,
                "end_time": end_time,
            }
        )

    return patterns


def parse_important_dates_table(lines, current_year: int):
    rows = []
    headers = None
    for raw in lines:
        line = clean_text(raw)
        cells = split_markdown_table_row(line)
        if not cells:
            continue
        if is_markdown_separator(cells):
            continue
        if headers is None:
            headers = [cell.lower() for cell in cells]
            continue

        row = dict(zip(headers, cells))
        start_text = row.get("start date", "")
        end_text = row.get("end date", "")
        description = row.get("event", "")
        if not start_text or not description:
            continue

        start_date = parse_month_day(start_text, current_year)
        end_date = parse_month_day(end_text, current_year) if end_text else start_date
        rows.append({"start": start_date, "end": end_date, "description": description})

    return rows


def parse_important_dates(path: Path):
    if not path.exists():
        return []

    rows = []
    current_year = TERM_YEAR
    lines = path.read_text(encoding="utf-8").splitlines()
    for raw in lines:
        line = clean_text(raw)
        if not line:
            continue

        term_match = re.match(r"^(?:Semester\s*:?\s*)?[A-Za-z]+\s+(\d{4})$", line, re.IGNORECASE)
        if term_match:
            current_year = int(term_match.group(1))
            break

    table_rows = parse_important_dates_table(lines, current_year)
    if table_rows:
        return table_rows

    for raw in lines:
        line = clean_text(raw)
        if not line:
            continue

        term_match = re.match(r"^(?:Semester\s*:?\s*)?[A-Za-z]+\s+(\d{4})$", line, re.IGNORECASE)
        if term_match:
            current_year = int(term_match.group(1))
            continue

        line = normalize_dash(line)
        m = re.match(r"^([A-Za-z]+\s+\d{1,2})(?:\s*-\s*([A-Za-z]+\s+)?(\d{1,2}))?\s+(.+)$", line)
        if not m:
            continue

        start_text, end_month, end_day, description = m.groups()
        start_date = parse_month_day(start_text, current_year)
        if end_day:
            month_name = end_month.strip() if end_month else calendar.month_name[start_date.month]
            end_date = parse_month_day(f"{month_name} {end_day}", current_year)
        else:
            end_date = start_date

        rows.append({"start": start_date, "end": end_date, "description": description})

    return rows


def important_dates_by_day(important_dates):
    by_day = defaultdict(list)
    for row in important_dates:
        current = row["start"]
        while current <= row["end"]:
            by_day[current].append(row["description"])
            current += timedelta(days=1)
    return by_day


def find_important_date(important_dates, pattern: str):
    regex = re.compile(pattern, re.IGNORECASE)
    for row in important_dates:
        if regex.search(row["description"]):
            return row
    return None


def term_bounds(important_dates):
    start = find_important_date(important_dates, r"Classes Begin")
    end = find_important_date(important_dates, r"Last Day of Classes")
    if not start or not end:
        return date(TERM_YEAR, 9, 2), date(TERM_YEAR, 12, 10)
    return start["start"], end["start"]


def class_suspended_dates(important_dates):
    suspended = set()
    for row in important_dates:
        description = row["description"].lower()
        if "classes suspended" in description or "thanksgiving recess" in description or "study period" in description:
            current = row["start"]
            while current <= row["end"]:
                suspended.add(current)
                current += timedelta(days=1)
    return suspended


def substitute_meeting_dates(important_dates):
    substitutes = set()
    for row in important_dates:
        if "substitute a monday schedule" in row["description"].lower():
            substitutes.add(row["start"])
    return substitutes


def build_class_meeting_dates(important_dates, lecture_weekdays):
    start, end = term_bounds(important_dates)
    suspended = class_suspended_dates(important_dates)
    substitutes = substitute_meeting_dates(important_dates)
    lecture_weekdays = set(lecture_weekdays)
    meetings = []
    current = start
    while current <= end:
        if (
            current in substitutes
            or current == end
            or (current.weekday() in lecture_weekdays and current not in suspended)
        ):
            meetings.append(current)
        current += timedelta(days=1)
    return meetings


def week_start_for_week(start: date, week: int) -> date:
    first_monday = start - timedelta(days=start.weekday())
    return first_monday + timedelta(weeks=week - 1)


def scheduled_weekday_date(
    term_start: date,
    week: int,
    weekday: int,
    suspended_dates: set[date],
    clamp_to_term_start: bool = True,
    shift_suspended: bool = True,
) -> date:
    candidate = week_start_for_week(term_start, week) + timedelta(days=weekday)
    if clamp_to_term_start and candidate < term_start:
        candidate = term_start
    while shift_suspended and candidate in suspended_dates:
        candidate += timedelta(days=1)
    return candidate


def course_week_for_date(term_start: date, event_date: date) -> int:
    first_monday = term_start - timedelta(days=term_start.weekday())
    return ((event_date - first_monday).days // 7) + 1


def nearby_important_dates(event_date: date, important_dates, window_days: int = 2):
    flags = []
    for row in important_dates:
        if not FLAGGABLE_IMPORTANT_DATE.search(row["description"]):
            continue
        if row["start"] <= event_date <= row["end"]:
            flags.append(row["description"])
            continue
        before = row["start"] - timedelta(days=window_days)
        after = row["end"] + timedelta(days=window_days)
        if before <= event_date <= after:
            flags.append(f"Near {row['description']}")
    return flags


def week_for_lecture_num(num: int) -> int:
    # Fallback grouping for lecture blocks.
    return ((num - 1) // 3) + 1


def week_for_entry(label: str, num: int) -> int:
    # Explicit week layout requested by the course schedule.
    if label in {"Lecture 1", "Lecture 2"}:
        return 1
    if label in {"Lecture 3", "Lecture 4", "Lecture 5"}:
        return 2
    if label in {"Lecture 6", "Lecture 7", "Lecture 8"}:
        return 3
    if label == "Quiz 1" or label in {"Lecture 9", "Lecture 10"}:
        return 4
    if label in {"Lecture 11", "Lecture 12", "Lecture 13"}:
        return 5
    if label in {"Lecture 14", "Lecture 15", "Lecture 16"}:
        return 6
    if label == "Quiz 2" or label in {"Lecture 17", "Lecture 18"}:
        return 7
    if label in {"Lecture 19", "Lecture 20", "Lecture 21"}:
        return 8
    if label in {"Lecture 22", "Lecture 23", "Lecture 24"}:
        return 9
    if label == "Quiz 3" or label in {"Lecture 25", "Lecture 26"}:
        return 10
    if label in {"Lecture 27", "Lecture 28", "Lecture 29"}:
        return 11
    if label in {"Lecture 30", "Lecture 31", "Lecture 32"}:
        return 12
    if label == "Quiz 4" or label in {"Lecture 33", "Lecture 34"}:
        return 13
    if label in {"Lecture 35", "Lecture 36"} or label == "Quiz 5":
        return 14
    return week_for_lecture_num(num)


def parse_quiz_schedule(path: Path):
    if not path.exists():
        return []

    rows = extract_table_after_heading(
        path.read_text(encoding="utf-8").splitlines(),
        "Quiz Schedule",
    )
    quiz_rows = []
    for row in rows:
        quiz = clean_text(row.get("quiz", ""))
        after_lecture = clean_text(row.get("after lecture", ""))
        if not quiz or not after_lecture:
            continue
        quiz_match = re.search(r"(\d+)", quiz)
        lecture_match = re.search(r"(\d+)", after_lecture)
        if not quiz_match or not lecture_match:
            continue
        status = clean_text(row.get("status", ""))
        notes = clean_text(row.get("notes", ""))
        quiz_rows.append(
            {
                "label": f"Quiz {int(quiz_match.group(1))}",
                "quiz_num": int(quiz_match.group(1)),
                "after_lecture": int(lecture_match.group(1)),
                "status": status,
                "notes": notes,
            }
        )
    return sorted(quiz_rows, key=lambda row: (row["after_lecture"], row["quiz_num"]))


def sequence_week_for_title(title: str):
    order = {
        "Lab 1": 1,
        "Lab 2": 2,
        "Lab 3": 3,
        "P1-1": 4,
        "Lab 4": 5,
        "Lab 5": 6,
        "P1-2": 7,
        "P2-1": 8,
        "Lab 6": 9,
        "P2-2": 10,
        "P2-3": 11,
        "Lab 7": 12,
        "Lab 8": 13,
    }
    return order.get(title)


def parse_lecture_summary(path: Path, quiz_schedule=None):
    text = path.read_text(encoding="utf-8")
    sections = {}
    current = None
    current_heading = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if re.match(r"^###\s+Lecture\s+.+", line):
            if current is not None and current_heading is not None:
                sections[current_heading] = current
            current_heading = line.split("###", 1)[1].strip()
            current = []
        elif current is not None:
            current.append(line)

    if current is not None and current_heading is not None:
        sections[current_heading] = current

    lecture_rows = []
    for heading, block in sections.items():
        m = re.match(r"^Lecture\s+(\d+)", heading)
        if not m:
            continue
        num = int(m.group(1))

        topic = ""
        for line in block:
            if "**Topic:**" in line:
                topic = line.split("**Topic:**", 1)[1].strip()

        lecture_rows.append(
            {
                "label": heading,
                "lecture_num": num,
                "week": week_for_entry(heading, num),
                "topic": topic,
                "kind": "lecture",
                "flags": [],
            }
        )

    quiz_schedule = quiz_schedule or []
    quizzes_by_anchor = defaultdict(list)
    for quiz in quiz_schedule:
        quizzes_by_anchor[quiz["after_lecture"]].append(quiz)

    sequenced_rows = []
    for row in sorted(lecture_rows, key=lambda item: item["lecture_num"]):
        sequenced_rows.append(row)
        for quiz in quizzes_by_anchor.get(row["lecture_num"], []):
            details = []
            if quiz["status"]:
                details.append(quiz["status"])
            if quiz["notes"]:
                details.append(quiz["notes"])
            sequenced_rows.append(
                {
                    "label": quiz["label"],
                    "lecture_num": quiz["quiz_num"],
                    "after_lecture": quiz["after_lecture"],
                    "week": row["week"],
                    "topic": "; ".join(details) if details else "Quiz in the scheduled course window.",
                    "kind": "quiz",
                    "flags": [],
                }
            )

    return sequenced_rows


def assign_course_dates(lecture_rows, important_dates, meeting_patterns):
    class_dates = build_class_meeting_dates(important_dates, meeting_patterns["lecture"])
    term_start, _ = term_bounds(important_dates)
    for row, meeting_date in zip(lecture_rows, class_dates):
        row["date"] = meeting_date
        row["week"] = course_week_for_date(term_start, meeting_date)
        row["flags"] = nearby_important_dates(meeting_date, important_dates)
    for row in lecture_rows[len(class_dates) :]:
        row["date"] = None
        row["flags"] = ["No available class meeting date"]
    return lecture_rows


def parse_lab_summary(path: Path):
    text = path.read_text(encoding="utf-8")
    sections = {}
    current = None
    current_heading = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if re.match(r"^###\s+(Lab\s+\d+|P\d+(?:-\d+|/\d+)*|Project\s+\d+.*)", line):
            if current is not None and current_heading is not None:
                sections[current_heading] = current
            current_heading = line.split("###", 1)[1].strip()
            current = []
        elif current is not None:
            current.append(line)

    if current is not None and current_heading is not None:
        sections[current_heading] = current

    lab_rows = []
    for heading, block in sections.items():
        # Match headings like: Lab 1: R Intro, P1-1: Project 1 Logistics, etc.
        title = heading.split(":", 1)[0].strip()

        lecture_anchor = ""
        purpose = ""
        objectives = []
        deliverables = []
        for i, line in enumerate(block):
            if "**Lecture anchor:**" in line:
                lecture_anchor = line.split("**Lecture anchor:**", 1)[1].strip()
            elif "**Purpose:**" in line:
                purpose = line.split("**Purpose:**", 1)[1].strip()
            elif "**Primary objectives supported**" in line:
                for nxt in block[i + 1 :]:
                    if nxt.startswith("- "):
                        objectives.append(nxt[2:].strip())
                    elif nxt.strip() == "":
                        continue
                    else:
                        break
            elif "**Deliverables**" in line:
                for nxt in block[i + 1 :]:
                    if nxt.startswith("- "):
                        deliverables.append(nxt[2:].strip())
                    elif nxt.strip() == "":
                        continue
                    else:
                        break

        # Use the explicit sequence order so that project sessions are included.
        week = sequence_week_for_title(title)

        if week is None and lecture_anchor:
            first_lecture = None
            m = re.search(r"(\d+)", lecture_anchor)
            if m:
                first_lecture = int(m.group(1))
            week = week_for_lecture_num(first_lecture) if first_lecture else None

        # Override the first few items to match the requested course layout.
        if title == "Lab 1":
            week = 1
            lecture_anchor = "Lecture 1"
        elif title == "Lab 2":
            week = 2
            lecture_anchor = "Lecture 4"
        elif title == "Lab 3":
            week = 3
            lecture_anchor = "Lecture 6"
        elif title == "P1-1":
            week = 4
            lecture_anchor = "Lecture 8"

        row = {
            "heading": heading,
            "title": title,
            "purpose": purpose,
            "lecture_anchor": lecture_anchor,
            "week": week,
            "objectives": " | ".join(objectives),
            "deliverables": " | ".join(deliverables),
        }

        if title == "P2-2/P2-3":
            lab_rows.extend(
                [
                    {**row, "title": "P2-2", "week": sequence_week_for_title("P2-2")},
                    {**row, "title": "P2-3", "week": sequence_week_for_title("P2-3")},
                ]
            )
        else:
            lab_rows.append(row)

    return lab_rows


def build_week_table(lecture_rows, lab_rows):
    # group lectures by week
    week_to_lectures = defaultdict(list)
    for row in lecture_rows:
        week_to_lectures[row["week"]].append(row)

    # build schedule rows for all relevant weeks, including project sessions
    all_weeks = set(week_to_lectures.keys())
    for lab in lab_rows:
        if lab["week"] is not None:
            all_weeks.add(lab["week"])

    rows = []
    for week in sorted(all_weeks):
        lectures = week_to_lectures.get(week, [])
        lecture_labels = ", ".join([r["label"] for r in lectures])
        lecture_topics = "; ".join(
            [f"{r['label']}: {r['topic']}" if r["topic"] else r["label"] for r in lectures]
        )
        flags = []
        for row in lectures:
            for flag in row.get("flags", []):
                flags.append(f"{row['label']}: {flag}")
        labs = []
        lab_deliverables = []
        for lab in lab_rows:
            if lab["week"] == week:
                anchor = lab["lecture_anchor"]
                labs.append(f"{lab['title']} ({anchor})" if anchor else lab["title"])
                if lab["deliverables"]:
                    lab_deliverables.append(f"{lab['title']}: {lab['deliverables']}")
                for flag in lab.get("flags", []):
                    flags.append(f"{lab['title']}: {flag}")

        rows.append(
            {
                "Week": week,
                "Lecture #": lecture_labels,
                "Lecture Topics": lecture_topics,
                "Labs": " | ".join(labs),
                "Lab Deliverables": " | ".join(lab_deliverables),
                "Instructor Flags": " | ".join(dict.fromkeys(flags)),
            }
        )

    return pd.DataFrame(rows)


def write_schedule_table(df: pd.DataFrame, xlsx_path: Path, sheet_name: str):
    if xlsx_path.exists():
        wb = load_workbook(xlsx_path)
        if sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            wb.remove(ws)
        ws = wb.create_sheet(title=sheet_name)
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name

    # write headers
    headers = list(df.columns)
    ws.append(headers)

    # write values
    for _, row in df.iterrows():
        ws.append([row[col] for col in headers])

    # style header row
    header_fill = PatternFill("solid", fgColor="D9EAF7")
    header_font = Font(bold=True)
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # auto-size columns
    for col in ws.columns:
        max_len = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if cell.value is not None:
                    max_len = max(max_len, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[column].width = min(max_len + 3, 80)

    wb.save(xlsx_path)


def write_markdown_table(df: pd.DataFrame, md_path: Path):
    headers = list(df.columns)
    lines = [
        "# Weekly Schedule",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]

    for _, row in df.iterrows():
        values = [str(row[col]).replace("|", "\\|") for col in headers]
        lines.append("| " + " | ".join(values) + " |")

    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def event_card(kind: str, title: str, details: str = "", meta: str = "", time_range: str = "") -> str:
    lines = [f'<article class="calendar-event calendar-event--{kind}">']
    lines.append(f'<div class="calendar-event__kind">{escape(kind.replace("-", " ").title())}</div>')
    lines.append(f'<h3>{escape(title)}</h3>')
    if time_range:
        lines.append(f'<p class="calendar-event__time">{escape(time_range)}</p>')
    if details:
        lines.append(f"<p>{escape(details)}</p>")
    if meta:
        lines.append(f'<p class="calendar-event__meta">{escape(meta)}</p>')
    lines.append("</article>")
    return "\n".join(lines)


def ics_escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\n", "\\n")
    )


def fold_ics_line(line: str) -> list[str]:
    if len(line) <= 75:
        return [line]
    folded = [line[:75]]
    rest = line[75:]
    while rest:
        folded.append(" " + rest[:74])
        rest = rest[74:]
    return folded


def write_ics_calendar(events, ics_path: Path):
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//MA213//Course Calendar//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        "X-WR-CALNAME:MA 213 Course Calendar",
        f"X-WR-TIMEZONE:{LOCAL_TIMEZONE}",
    ]

    for event_date in sorted(events):
        for index, item in enumerate(events[event_date], start=1):
            title = item["title"]
            details = item.get("details", "")
            meta = item.get("meta", "")
            description = details if not meta else f"{details}\n{meta}" if details else meta
            uid_text = re.sub(r"[^A-Za-z0-9]+", "-", f"{event_date}-{index}-{title}").strip("-")
            event_lines = [
                "BEGIN:VEVENT",
                f"UID:{uid_text}@ma213-course-calendar",
                "DTSTAMP:20260101T000000Z",
            ]
            start_time = item.get("start_time", "")
            end_time = item.get("end_time", "")
            if start_time and end_time:
                start_dt = time_for_ics(event_date, start_time)
                end_dt = time_for_ics(event_date, end_time)
                event_lines.extend(
                    [
                        f"DTSTART;TZID={LOCAL_TIMEZONE}:{start_dt:%Y%m%dT%H%M%S}",
                        f"DTEND;TZID={LOCAL_TIMEZONE}:{end_dt:%Y%m%dT%H%M%S}",
                    ]
                )
            elif end_time:
                due_dt = time_for_ics(event_date, end_time)
                event_lines.append(f"DTSTART;TZID={LOCAL_TIMEZONE}:{due_dt:%Y%m%dT%H%M%S}")
            elif start_time:
                start_dt = time_for_ics(event_date, start_time)
                event_lines.append(f"DTSTART;TZID={LOCAL_TIMEZONE}:{start_dt:%Y%m%dT%H%M%S}")
            else:
                next_day = event_date + timedelta(days=1)
                event_lines.extend(
                    [
                        f"DTSTART;VALUE=DATE:{event_date:%Y%m%d}",
                        f"DTEND;VALUE=DATE:{next_day:%Y%m%d}",
                    ]
                )
            event_lines.append(f"SUMMARY:{ics_escape(title)}")
            if description:
                event_lines.append(f"DESCRIPTION:{ics_escape(description)}")
            event_lines.append("END:VEVENT")
            for line in event_lines:
                lines.extend(fold_ics_line(line))

    lines.append("END:VCALENDAR")
    ics_path.write_text("\r\n".join(lines) + "\r\n", encoding="utf-8")


def build_calendar_events(lecture_rows, lab_rows, important_dates, meeting_patterns):
    events = defaultdict(list)
    important_by_day = important_dates_by_day(important_dates)
    term_start, term_end = term_bounds(important_dates)
    suspended = class_suspended_dates(important_dates)
    lab_weekday = meeting_patterns["lab"][0]
    lab_deliverable_weekday = meeting_patterns["lab_deliverable"][0]

    for row in lecture_rows:
        meeting_date = row.get("date")
        if meeting_date is None:
            continue
        label = row["label"]
        kind = row.get("kind", "quiz" if label.startswith("Quiz") else "lecture")
        details = row["topic"] or "Quiz in the scheduled course window."
        meta = " | ".join(row.get("flags", []))
        start_time, end_time = event_time_range(meeting_patterns, "lecture")
        events[meeting_date].append(
            {
                "kind": kind,
                "title": label,
                "details": details,
                "meta": meta,
                "start_time": start_time,
                "end_time": end_time,
            }
        )

    for lab in lab_rows:
        if lab["week"] is None:
            continue
        lab_date = scheduled_weekday_date(term_start, lab["week"], lab_weekday, suspended)
        lab["flags"] = nearby_important_dates(lab_date, important_dates)
        kind = "lab"
        start_time, end_time = event_time_range(meeting_patterns, "lab")
        meta_parts = []
        if lab["lecture_anchor"]:
            meta_parts.append(f"Anchor: {lab['lecture_anchor']}")
        if lab["deliverables"]:
            meta_parts.append(f"Deliverables: {lab['deliverables']}")
        meta_parts.extend(lab.get("flags", []))
        events[lab_date].append(
            {
                "kind": kind,
                "title": lab["title"],
                "details": lab["purpose"],
                "meta": " | ".join(meta_parts),
                "start_time": start_time,
                "end_time": end_time,
            }
        )

        if lab["deliverables"]:
            deliverable_date = scheduled_weekday_date(
                term_start,
                lab["week"],
                lab_deliverable_weekday,
                suspended,
            )
            if term_start <= deliverable_date <= term_end:
                start_time, end_time = event_time_range(meeting_patterns, "lab_deliverable")
                events[deliverable_date].append(
                    {
                        "kind": "lab-deliverable",
                        "title": f"{lab['title']} Deliverables Due",
                        "details": lab["deliverables"],
                        "start_time": start_time,
                        "end_time": end_time,
                    }
                )

    max_week = max([row["week"] for row in lecture_rows] + [row["week"] for row in lab_rows if row["week"]])
    for week in range(1, max_week + 1):
        for weekday in meeting_patterns["discussion"]:
            discussion_date = scheduled_weekday_date(term_start, week, weekday, suspended, clamp_to_term_start=False)
            if term_start <= discussion_date <= term_end:
                start_time, end_time = event_time_range(meeting_patterns, "discussion")
                events[discussion_date].append(
                    {
                        "kind": "discussion",
                        "title": "Discussion Section",
                        "details": "",
                        "start_time": start_time,
                        "end_time": end_time,
                    }
                )
        for office_hour in meeting_patterns["office_hour_patterns"]:
            for weekday in office_hour["weekdays"]:
                office_hours_date = scheduled_weekday_date(
                    term_start,
                    week,
                    weekday,
                    suspended,
                    clamp_to_term_start=False,
                    shift_suspended=False,
                )
                if term_start <= office_hours_date <= term_end and office_hours_date not in suspended:
                    events[office_hours_date].append(
                        {
                            "kind": "office-hours",
                            "title": office_hour["title"],
                            "details": "",
                            "start_time": office_hour["start_time"],
                            "end_time": office_hour["end_time"],
                        }
                    )
        for weekday in meeting_patterns["homework"]:
            homework_date = scheduled_weekday_date(term_start, week, weekday, suspended, clamp_to_term_start=False)
            if term_start <= homework_date <= term_end:
                start_time, end_time = event_time_range(meeting_patterns, "homework")
                events[homework_date].append(
                    {
                        "kind": "homework",
                        "title": f"Homework Week {week}",
                        "details": "Weekly homework component.",
                        "start_time": start_time,
                        "end_time": end_time,
                    }
                )

    for day, descriptions in important_by_day.items():
        for description in descriptions:
            events[day].insert(
                0,
                {
                    "kind": "important-date",
                    "title": "Academic Calendar",
                    "details": description,
                },
            )

    return events


def month_grid_dates(year: int, month: int):
    first = date(year, month, 1)
    days_since_sunday = (first.weekday() + 1) % 7
    start = first - timedelta(days=days_since_sunday)
    return [start + timedelta(days=i) for i in range(42)]


def months_to_render(important_dates):
    term_start, term_end = term_bounds(important_dates)
    latest = term_end
    for row in important_dates:
        latest = max(latest, row["end"])

    months = []
    current = date(term_start.year, term_start.month, 1)
    final = date(latest.year, latest.month, 1)
    while current <= final:
        months.append(current)
        if current.month == 12:
            current = date(current.year + 1, 1, 1)
        else:
            current = date(current.year, current.month + 1, 1)
    return months


def write_calendar_markdown(lecture_rows, lab_rows, important_dates, meeting_patterns, md_path: Path):
    events = build_calendar_events(lecture_rows, lab_rows, important_dates, meeting_patterns)
    class_dates = build_class_meeting_dates(important_dates, meeting_patterns["lecture"])
    term_start, term_end = term_bounds(important_dates)
    term_start_label = f"{term_start.strftime('%B')} {term_start.day}, {term_start.year}"
    term_end_label = f"{term_end.strftime('%B')} {term_end.day}, {term_end.year}"
    lines = [
        "# Calendar View",
        "",
        '<div class="calendar-note">',
        f"This month view is generated from course summaries and `instructor_inputs/important_dates.md`. It assigns lectures and quizzes to class-meeting dates from {term_start_label} through {term_end_label}; exact rooms, section times, and office-hour locations should follow the current syllabus.",
        "</div>",
        "",
        '<details class="calendar-download-menu">',
        '<summary class="calendar-download-trigger">Download Calendar</summary>',
        '<div class="calendar-download-options">',
        '<a class="calendar-download-option" href="../course_calendar.ics" download>Google Calendar</a>',
        '<a class="calendar-download-option" href="../course_calendar.ics" download>Apple Calendar</a>',
        '<a class="calendar-download-option" href="../course_calendar.ics" download>Outlook</a>',
        "</div>",
        "</details>",
        "",
    ]

    if len(lecture_rows) > len(class_dates):
        missing = len(lecture_rows) - len(class_dates)
        lines.extend(
            [
                '<div class="calendar-warning">',
                f"{missing} lecture/quiz item(s) could not be assigned because there are not enough class-meeting dates.",
                "</div>",
                "",
            ]
        )

    for month_start in months_to_render(important_dates):
        month = month_start.month
        year = month_start.year
        month_name = calendar.month_name[month]
        lines.append(f'<section class="calendar-month" aria-labelledby="{month_name.lower()}-{year}">')
        lines.append(f'<h2 id="{month_name.lower()}-{year}">{month_name} {year}</h2>')
        lines.append('<div class="calendar-month-grid">')
        for weekday in CALENDAR_WEEKDAYS:
            lines.append(f'<div class="calendar-weekday">{escape(weekday)}</div>')

        for day in month_grid_dates(year, month):
            classes = ["calendar-date"]
            if day.month != month:
                classes.append("calendar-date--outside")
            if day < term_start or day > term_end:
                classes.append("calendar-date--term-edge")
            lines.append(f'<section class="{" ".join(classes)}">')
            lines.append(f'<div class="calendar-date__number">{day.day}</div>')
            day_events = events.get(day, []) if day.month == month else []
            for item in day_events:
                lines.append(
                    event_card(
                        item["kind"],
                        item["title"],
                        item.get("details", ""),
                        item.get("meta", ""),
                        format_time_range(item.get("start_time", ""), item.get("end_time", "")),
                    )
                )
            if not day_events and day.month == month:
                lines.append('<p class="calendar-empty">No events</p>')
            lines.append("</section>")
        lines.append("</div>")
        lines.append("</section>")
        lines.append("")

    md_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    GENERATED_OUTPUTS.mkdir(exist_ok=True)

    important_dates = parse_important_dates(IMPORTANT_DATES_FILE)
    meeting_patterns = parse_meeting_patterns(LECTURE_FILE, LAB_FILE)
    quiz_rows = parse_quiz_schedule(QUIZ_SCHEDULE_FILE)
    lecture_rows = parse_lecture_summary(LECTURE_FILE, quiz_rows)
    lecture_rows = assign_course_dates(lecture_rows, important_dates, meeting_patterns)
    lab_rows = parse_lab_summary(LAB_FILE)
    build_calendar_events(lecture_rows, lab_rows, important_dates, meeting_patterns)

    df = build_week_table(lecture_rows, lab_rows)
    write_schedule_table(df, XLSX_FILE, OUTPUT_SHEET)
    write_markdown_table(df, OUTPUT_MD)
    write_calendar_markdown(lecture_rows, lab_rows, important_dates, meeting_patterns, OUTPUT_CALENDAR_MD)
    calendar_events = build_calendar_events(lecture_rows, lab_rows, important_dates, meeting_patterns)
    write_ics_calendar(calendar_events, OUTPUT_ICS)

    print(f"Processed {len(lecture_rows)} lecture entries and {len(lab_rows)} lab/project entries.")
    print(f"Wrote {len(df)} rows to {XLSX_FILE.name} -> {OUTPUT_SHEET}")
    print(f"Wrote markdown schedule to {OUTPUT_MD.name}")
    print(f"Wrote calendar view to {OUTPUT_CALENDAR_MD.name}")
    print(f"Wrote calendar download to {OUTPUT_ICS.name}")
