from pathlib import Path
import re
from collections import defaultdict

import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

ROOT = Path(__file__).resolve().parent
LECTURE_FILE = ROOT / "lecture_summary.md"
LAB_FILE = ROOT / "lab_summary.md"
XLSX_FILE = ROOT / "Weekly Schedules.xlsx"
OUTPUT_SHEET = "AutoGenerated Schedule"
OUTPUT_MD = ROOT / "weekly_schedule.md"


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def week_for_lecture_num(num: int) -> int:
    # Fallback grouping for lecture blocks.
    return ((num - 1) // 3) + 1


def week_for_entry(label: str, num: int) -> int:
    # Explicit week layout requested by the course schedule.
    if label in {"Lecture 1", "Lecture 2"}:
        return 1
    if label in {"Lecture 3", "Lecture 4", "Lecture 5"}:
        return 2
    if label in {"Lecture 6", "Lecture 7", "Lecture 8"}:
        return 3
    if label == "Quiz 1" or label in {"Lecture 9", "Lecture 10"}:
        return 4
    if label in {"Lecture 11", "Lecture 12", "Lecture 13"}:
        return 5
    if label in {"Lecture 14", "Lecture 15", "Lecture 16"}:
        return 6
    if label == "Quiz 2" or label in {"Lecture 17", "Lecture 18"}:
        return 7
    if label in {"Lecture 19", "Lecture 20", "Lecture 21"}:
        return 8
    if label in {"Lecture 22", "Lecture 23", "Lecture 24"}:
        return 9
    if label == "Quiz 3" or label in {"Lecture 25", "Lecture 26"}:
        return 10
    if label in {"Lecture 27", "Lecture 28", "Lecture 29"}:
        return 11
    if label in {"Lecture 30", "Lecture 31", "Lecture 32"}:
        return 12
    if label == "Quiz 4" or label in {"Lecture 33", "Lecture 34"}:
        return 13
    if label in {"Lecture 35", "Lecture 36"} or label == "Quiz 5":
        return 14
    return week_for_lecture_num(num)


def sequence_week_for_title(title: str):
    order = {
        "Lab 1": 1,
        "Lab 2": 2,
        "Lab 3": 3,
        "P1-1": 4,
        "Lab 4": 5,
        "Lab 5": 6,
        "P1-2": 7,
        "P2-1": 8,
        "Lab 6": 9,
        "P2-2": 10,
        "P2-3": 11,
        "Lab 7": 12,
    }
    return order.get(title)


def parse_lecture_summary(path: Path):
    text = path.read_text(encoding="utf-8")
    sections = {}
    current = None
    current_heading = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if re.match(r"^###\s+(Lecture|Quiz)\s+.+", line):
            if current is not None and current_heading is not None:
                sections[current_heading] = current
            current_heading = line.split("###", 1)[1].strip()
            current = []
        elif current is not None:
            current.append(line)

    if current is not None and current_heading is not None:
        sections[current_heading] = current

    lecture_rows = []
    for heading, block in sections.items():
        m = re.match(r"^(Lecture|Quiz)\s+(\d+)", heading)
        if not m:
            continue
        kind, num = m.groups()
        num = int(num)

        topic = ""
        for line in block:
            if "**Topic:**" in line:
                topic = line.split("**Topic:**", 1)[1].strip()

        lecture_rows.append(
            {
                "label": heading,
                "lecture_num": num,
                "week": week_for_entry(heading, num),
                "topic": topic,
            }
        )

    return lecture_rows


def parse_lab_summary(path: Path):
    text = path.read_text(encoding="utf-8")
    sections = {}
    current = None
    current_heading = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if re.match(r"^###\s+(Lab\s+\d+|P\d+(?:-\d+|/\d+)*|Project\s+\d+.*)", line):
            if current is not None and current_heading is not None:
                sections[current_heading] = current
            current_heading = line.split("###", 1)[1].strip()
            current = []
        elif current is not None:
            current.append(line)

    if current is not None and current_heading is not None:
        sections[current_heading] = current

    lab_rows = []
    for heading, block in sections.items():
        # Match headings like: Lab 1: R Intro, P1-1: Project 1 Logistics, etc.
        title = heading.split(":", 1)[0].strip()

        lecture_anchor = ""
        purpose = ""
        objectives = []
        deliverables = []
        for i, line in enumerate(block):
            if "**Lecture anchor:**" in line:
                lecture_anchor = line.split("**Lecture anchor:**", 1)[1].strip()
            elif "**Purpose:**" in line:
                purpose = line.split("**Purpose:**", 1)[1].strip()
            elif "**Primary objectives supported**" in line:
                for nxt in block[i + 1 :]:
                    if nxt.startswith("- "):
                        objectives.append(nxt[2:].strip())
                    elif nxt.strip() == "":
                        continue
                    else:
                        break
            elif "**Deliverables**" in line:
                for nxt in block[i + 1 :]:
                    if nxt.startswith("- "):
                        deliverables.append(nxt[2:].strip())
                    elif nxt.strip() == "":
                        continue
                    else:
                        break

        # Use the explicit sequence order so that project sessions are included.
        week = sequence_week_for_title(title)

        if week is None and lecture_anchor:
            first_lecture = None
            m = re.search(r"(\d+)", lecture_anchor)
            if m:
                first_lecture = int(m.group(1))
            week = week_for_lecture_num(first_lecture) if first_lecture else None

        # Override the first few items to match the requested course layout.
        if title == "Lab 1":
            week = 1
            lecture_anchor = "Lecture 1"
        elif title == "Lab 2":
            week = 2
            lecture_anchor = "Lecture 4"
        elif title == "Lab 3":
            week = 3
            lecture_anchor = "Lecture 6"
        elif title == "P1-1":
            week = 4
            lecture_anchor = "Lecture 8"

        row = {
            "heading": heading,
            "title": title,
            "purpose": purpose,
            "lecture_anchor": lecture_anchor,
            "week": week,
            "objectives": " | ".join(objectives),
            "deliverables": " | ".join(deliverables),
        }

        if title == "P2-2/P2-3":
            lab_rows.extend(
                [
                    {**row, "title": "P2-2", "week": sequence_week_for_title("P2-2")},
                    {**row, "title": "P2-3", "week": sequence_week_for_title("P2-3")},
                ]
            )
        else:
            lab_rows.append(row)

    return lab_rows


def build_week_table(lecture_rows, lab_rows):
    # group lectures by week
    week_to_lectures = defaultdict(list)
    for row in lecture_rows:
        week_to_lectures[row["week"]].append(row)

    # build schedule rows for all relevant weeks, including project sessions
    all_weeks = set(week_to_lectures.keys())
    for lab in lab_rows:
        if lab["week"] is not None:
            all_weeks.add(lab["week"])

    rows = []
    for week in sorted(all_weeks):
        lectures = week_to_lectures.get(week, [])
        lecture_labels = ", ".join([r["label"] for r in lectures])
        lecture_topics = "; ".join(
            [f"{r['label']}: {r['topic']}" if r["topic"] else r["label"] for r in lectures]
        )
        labs = []
        lab_deliverables = []
        for lab in lab_rows:
            if lab["week"] == week:
                anchor = lab["lecture_anchor"]
                labs.append(f"{lab['title']} ({anchor})" if anchor else lab["title"])
                if lab["deliverables"]:
                    lab_deliverables.append(f"{lab['title']}: {lab['deliverables']}")

        rows.append(
            {
                "Week": week,
                "Lecture #": lecture_labels,
                "Lecture Topics": lecture_topics,
                "Labs": " | ".join(labs),
                "Lab Deliverables": " | ".join(lab_deliverables),
            }
        )

    return pd.DataFrame(rows)


def write_schedule_table(df: pd.DataFrame, xlsx_path: Path, sheet_name: str):
    if xlsx_path.exists():
        wb = load_workbook(xlsx_path)
        if sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            wb.remove(ws)
        ws = wb.create_sheet(title=sheet_name)
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name

    # write headers
    headers = list(df.columns)
    ws.append(headers)

    # write values
    for _, row in df.iterrows():
        ws.append([row[col] for col in headers])

    # style header row
    header_fill = PatternFill("solid", fgColor="D9EAF7")
    header_font = Font(bold=True)
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # auto-size columns
    for col in ws.columns:
        max_len = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if cell.value is not None:
                    max_len = max(max_len, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[column].width = min(max_len + 3, 80)

    wb.save(xlsx_path)


def write_markdown_table(df: pd.DataFrame, md_path: Path):
    headers = list(df.columns)
    lines = [
        "# Weekly Schedule",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]

    for _, row in df.iterrows():
        values = [str(row[col]).replace("|", "\\|") for col in headers]
        lines.append("| " + " | ".join(values) + " |")

    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    lecture_rows = parse_lecture_summary(LECTURE_FILE)
    lab_rows = parse_lab_summary(LAB_FILE)

    df = build_week_table(lecture_rows, lab_rows)
    write_schedule_table(df, XLSX_FILE, OUTPUT_SHEET)
    write_markdown_table(df, OUTPUT_MD)

    print(f"Processed {len(lecture_rows)} lecture entries and {len(lab_rows)} lab/project entries.")
    print(f"Wrote {len(df)} rows to {XLSX_FILE.name} -> {OUTPUT_SHEET}")
    print(f"Wrote markdown schedule to {OUTPUT_MD.name}")
