---
title: "MA213 - Fall 2025"
output:
  pdf_document: default
  html_document:
    code_download: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

# Basic Statistics and Probability

## Project 1 Design

### Pre-lab activities

-   Let's make group. Each group should have 4-5 people.

-   Little bit overview of R markdown file.

## Lab Activities 

1.  Get familiar with your group members. Name for your group.
2.  You can start discuss interesting questions. How you can obtain the data.

## Project 1

### Each group work with

### 1. Exploring Categorical Variables :

-   Summarize and visualize two categorical variables.
-   Derive a research question(s) based on the findings.

### 2. Exploring Numerical Variables :

-   Summarize and visualize two numerical variables.
-   Formulate a research question(s) based on the findings.

### Important Note

-   Each member has to have a specific role.
-   Role can include data finding, categorical variables part, numerical variable part, ...
-   If your dataset has two categorical variables and two numerical variables, then one dataset is fine. Otherwise, two datasets should be considered.

### Resources for public data

Kaggle : <https://www.kaggle.com/datasets>

R datasets :

### R code Rule

### Citation Rule

### 
